# @format

# issueì—ì„œ convert ëì„ ë•Œ
# 1. projectì— ì¶”ê°€
# 2. issueì— label ì¶”ê°€

name: Add to Project

on:
  issues:
    types:
      - opened

jobs:
  title-to-label:
    name: Add title to labels
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          keywords: |
            ğŸ”®
            epic
          labels: |
            epic
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          keywords: |
            ğŸ“—
          labels: |
            story
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
          keywords: |
            âœ…
          labels: |
            feature

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/boostcampwm2023/projects/19/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
